# Generated by Django 2.2.24 on 2022-06-10 06:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0005_likes_and_complaints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likes_and_complaints',
            options={'verbose_name_plural': 'Likes_And_Complaints'},
        ),
        migrations.AddField(
            model_name='flat',
            name='likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
