# Generated by Django 2.2.24 on 2022-06-10 08:20

from django.db import migrations

import phonenumbers


def parse_phone_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    all_flats = Flat.objects.all()
    for flat in all_flats.iterator():
        parsed_number = phonenumbers.parse(flat.owners_phonenumber, "RU")
        if phonenumbers.is_valid_number(parsed_number):
            flat.owner_pure_phone = phonenumbers.format_number(
                parsed_number,
                phonenumbers.PhoneNumberFormat.E164,
            )
        else:
            flat.owner_pure_phone = None
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20220610_1422'),
    ]

    operations = [
        migrations.RunPython(parse_phone_number,)
    ]
