# Generated by Django 2.2.24 on 2022-06-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20220611_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owners_phonenumber',
            field=models.CharField(db_index=True, max_length=20, null=True, verbose_name='Номер владельца'),
        ),
    ]
