# Generated by Django 2.2.24 on 2022-06-11 05:18

from django.db import migrations


def add_apartments(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        owner = Owner.objects.get(full_name=flat.owner_name)
        owner.flats.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20220611_1112'),
    ]

    operations = [
        migrations.RunPython(add_apartments,),
    ]
